# Generated by Django 3.2 on 2022-01-07 17:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('turtles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='turtles',
            name='sponsored_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='turtle_sponsor',
            name='sponsored_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
