# Generated by Django 3.2 on 2022-01-07 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchandise', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donate',
            options={'verbose_name_plural': 'Donations'},
        ),
        migrations.AlterModelOptions(
            name='merch',
            options={'verbose_name_plural': 'Merch'},
        ),
    ]
