# Generated by Django 3.2 on 2022-01-10 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchandise', '0003_turtles'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Turtles',
        ),
    ]
